const currencyData = [
  { label: "USD - United States Dollar", value: "USD", symbol: "$" },
 
  { label: "EUR - Euro (Austria)", value: "EUR_AT", symbol: "€" },
  { label: "EUR - Euro (Ireland)", value: "EUR_IE", symbol: "€" },
  { label: "EUR - Euro (Luxembourg)", value: "EUR_LU", symbol: "€" },
  { label: "EUR - Euro (Finland)", value: "EUR_FI", symbol: "€" },
  { label: "EUR - Euro (Slovakia)", value: "EUR_SK", symbol: "€" },
  { label: "EUR - Euro (Slovenia)", value: "EUR_SI", symbol: "€" },
  { label: "EUR - Euro (Estonia)", value: "EUR_EE", symbol: "€" },
  { label: "EUR - Euro (Latvia)", value: "EUR_LV", symbol: "€" },
  { label: "EUR - Euro (Lithuania)", value: "EUR_LT", symbol: "€" },
  { label: "EUR - Euro (Cyprus)", value: "EUR_CY", symbol: "€" },
  { label: "EUR - Euro (Malta)", value: "EUR_MT", symbol: "€" },
  { label: "GBP - British Pound", value: "GBP", symbol: "£" },
  { label: "JPY - Japanese Yen", value: "JPY", symbol: "¥" },
  { label: "CNY - Chinese Yuan", value: "CNY", symbol: "¥" },
  { label: "AUD - Australian Dollar", value: "AUD", symbol: "$" },
  { label: "CAD - Canadian Dollar", value: "CAD", symbol: "$" },
  { label: "CHF - Swiss Franc", value: "CHF", symbol: "CHF" },
  { label: "SEK - Swedish Krona", value: "SEK", symbol: "kr" },
  { label: "DKK - Danish Krone", value: "DKK", symbol: "kr" },
  { label: "NOK - Norwegian Krone", value: "NOK", symbol: "kr" },
  { label: "NZD - New Zealand Dollar", value: "NZD", symbol: "$" },
  { label: "SGD - Singapore Dollar", value: "SGD", symbol: "$" },
  { label: "HKD - Hong Kong Dollar", value: "HKD", symbol: "$" },
  { label: "CZK - Czech Koruna", value: "CZK", symbol: "Kč" },
  { label: "HUF - Hungarian Forint", value: "HUF", symbol: "Ft" },
  { label: "RON - Romanian Leu", value: "RON", symbol: "lei" },
  { label: "BGN - Bulgarian Lev", value: "BGN", symbol: "лв" },
  { label: "HRK - Croatian Kuna", value: "HRK", symbol: "kn" },
  { label: "INR - Indian Rupee", value: "INR", symbol: "₹" },
  { label: "KRW - South Korean Won", value: "KRW", symbol: "₩" },
  { label: "THB - Thai Baht", value: "THB", symbol: "฿" },
  { label: "VND - Vietnamese Dong", value: "VND", symbol: "₫" },
  { label: "MYR - Malaysian Ringgit", value: "MYR", symbol: "RM" },
  { label: "PHP - Philippine Peso", value: "PHP", symbol: "₱" },
  { label: "BRL - Brazilian Real", value: "BRL", symbol: "R$" },
  { label: "ARS - Argentine Peso", value: "ARS", symbol: "$" },
  { label: "CLP - Chilean Peso", value: "CLP", symbol: "$" },
  { label: "COP - Colombian Peso", value: "COP", symbol: "$" },
  { label: "PEN - Peruvian Sol", value: "PEN", symbol: "S/" },
  { label: "ZAR - South African Rand", value: "ZAR", symbol: "R" },
  { label: "NGN - Nigerian Naira", value: "NGN", symbol: "₦" },
  { label: "EGP - Egyptian Pound", value: "EGP", symbol: "£" },
  { label: "KES - Kenyan Shilling", value: "KES", symbol: "KSh" },
  { label: "GHS - Ghanaian Cedi", value: "GHS", symbol: "GH₵" },
  { label: "AED - United Arab Emirates Dirham", value: "AED", symbol: "AED" },
  { label: "SAR - Saudi Riyal", value: "SAR", symbol: "SAR" },
  { label: "QAR - Qatari Riyal", value: "QAR", symbol: "QAR" },
  { label: "ILS - Israeli Shekel", value: "ILS", symbol: "₪" },
  { label: "TRY - Turkish Lira", value: "TRY", symbol: "₺" },
  { label: "Choose currency", value: "...", symbol: "......" },
];

export default currencyData;
